- name: Upgrade de todos os pacotes do s.o #nome da task
  yum: #já é um módulo do próprio ansible
    name: '*' #nome de qual pacote quer atualizar. Neste caso, são todos
    state: latest #atualizar para a ultima versao
- name: instalacao do git client
  yum:
    name: git
    state: latest